version: '3.5'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8802:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=phbit@phbit.com.br
      - PGADMIN_DEFAULT_PASSWORD=dev
    networks:
      - postgresnetwork

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 8801:5432
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=project
    volumes:
      - ./banco:/var/lib/postgresql/data
    networks:
      - postgresnetwork

networks:
  postgresnetwork:
    driver: bridge
